# Generated by Django 4.0.2 on 2022-11-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('animal', models.CharField(max_length=100)),
                ('amount', models.IntegerField(max_length=12)),
                ('period', models.IntegerField(max_length=2)),
                ('since', models.CharField(max_length=12)),
                ('rodo_agreement', models.BooleanField()),
                ('data_agreement', models.BooleanField()),
            ],
        ),
    ]
