# Generated by Django 4.0.2 on 2022-11-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='period',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
